[versions]
kotter = "1.3.0-SNAPSHOT"
#------------------------
dokka = "2.0.0"
jline = "3.30.4"
kotlinx-coroutines = "1.7.3"
kotlin = "2.2.0"
kover = "0.9.4"
truthish = "1.0.3"
vanniktech-publish = "0.34.0"

[libraries]
jcip-annotations = { module = "net.jcip:jcip-annotations", version = "1.0" }
jetbrains-dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
jline-terminal-core = { module = "org.jline:jline-terminal", version.ref = "jline" }
jline-terminal-jni = { module = "org.jline:jline-terminal-jni", version.ref = "jline" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-multiplatform-plugin = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
truthish = { module = "com.varabyte.truthish:truthish", version.ref = "truthish" }
vanniktech-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-publish" }

[plugins]
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-publish" }

[bundles]
jline = ["jline-terminal-core", "jline-terminal-jni"]