[versions]
jline = "3.21.0"
kotlin = "1.7.20"
kotlinx-coroutines = "1.6.4"
kotter = "1.1.0-SNAPSHOT"
kover = "0.6.1"
nexus-publish = "1.2.0"
okhttp = "4.9.3"
truthish = "0.6.3"

[libraries]
jcip-annotations = { module = "net.jcip:jcip-annotations", version = "1.0" }
jline-terminal-core = { module = "org.jline:jline-terminal", version.ref = "jline" }
jline-terminal-jansi = { module = "org.jline:jline-terminal-jansi", version.ref = "jline" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
truthish = { module = "com.varabyte.truthish:truthish", version.ref = "truthish" }

[plugins]
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }